### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by cgisky1980** [FFengIll/FFengIll#1]
在 bert.cpp 项目看到您的PR
我们一个AI的项目   https://github.com/cgisky1980/ai00_rwkv_server

需要一个无依赖的  SentenceTransformers （sbert） server  提供 t2v 向量数据

目前bert.cpp 貌似还不支持中文，请求帮助

**Comment by FFengIll** [comment]
@cgisky1980 抱歉，我意外地忽视了这个issue。
由于各种原因，我并没有在public fork中继续，但截止目前，最重要的尝试都提交到了public fork中。
